### ISSUE TITLE
Implement the Project Member Endpoint

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#150]
https://github.com/remsfal/remsfal-backend/blob/8631892d64abbc405a272e3152b144f220ee259c/remsfal-service/src/main/java/de/remsfal/service/boundary/ProjectResource.java#L88

https://github.com/remsfal/remsfal-backend/blob/8631892d64abbc405a272e3152b144f220ee259c/remsfal-service/src/main/java/de/remsfal/service/boundary/ProjectResource.java#L97

https://github.com/remsfal/remsfal-backend/blob/8631892d64abbc405a272e3152b144f220ee259c/remsfal-service/src/main/java/de/remsfal/service/boundary/ProjectResource.java#L106

https://github.com/remsfal/remsfal-backend/blob/8631892d64abbc405a272e3152b144f220ee259c/remsfal-service/src/main/java/de/remsfal/service/boundary/ProjectResource.java#L115

**Comment by alexeyleping** [comment]
Guys, I have put together a project but there is no class ImmutableProjectJson.class Can you put it on?
![Screenshot from 2024-06-20 10-29-07](https://github.com/remsfal/remsfal-backend/assets/103263545/82a080b4-99bc-415a-8cc3-42d95558cf9f)

**Comment by astanik** [comment]
@alexeyleping The ImmutableProjectJson.class is a generated class by Immutables. Hier you can find further information about Immutables: https://immutables.github.io/

If you are using IntelliJ, the follwoing information may be usefull for you: https://immutables.github.io/apt.html

**Comment by alexeyleping** [comment]
Thanks, great advice, everything worked out

**Comment by alexeyleping** [comment]
https://github.com/remsfal/remsfal-backend/pull/158
