### ISSUE TITLE
Implement the Building Endpoint

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#152]
https://github.com/remsfal/remsfal-backend/blob/8631892d64abbc405a272e3152b144f220ee259c/remsfal-core/src/main/java/de/remsfal/core/api/project/BuildingEndpoint.java#L27

**Comment by alexeyleping** [comment]
https://github.com/remsfal/remsfal-backend/pull/161
 public BuildingJson getBuilding(String projectId, String propertyId, String buildingId)
implemented via the building Id, if needed in a different way, please explain what is required

**Comment by HassanAlhawari1998** [comment]
An endpoint is needed for fetching all buildings associated with a specific 'propertyId' and another endpoint is needed for updating details of existing buildings.

**Comment by astanik** [comment]
@alexeyleping I specified the required operations for the BuildingEndpoint in #185 
Would you like to take over this issue and complete your pull request?

**Comment by alexeyleping** [comment]
@astanik yes, I will do it, but I will be gone for 2 weeks, I'm going on vacation, I will be gone for a little more than 2 weeks, it needs to be done urgently or are we in no hurry?
