### ISSUE TITLE
Create snapshot image on Push to main branch

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#163]

**Comment by astanik** [comment]
@MaxBuening Unfortunately the workflow failed. See https://github.com/remsfal/remsfal-backend/actions/runs/9774343379/job/26982398887

**Comment by MaxBuening** [comment]
I made a new pull request with corretions 
i think it was because i had a wrong path to the .jar file in the dockerfile

**Comment by astanik** [comment]
@MaxBuening The image is now available at https://github.com/remsfal/remsfal-backend/pkgs/container/remsfal-backend
