### ISSUE TITLE
Implement API Endpoints for Fetching and Updating Object Data

### ISSUE THREAD

**Issue by HassanAlhawari1998** [remsfal/remsfal-backend#175]
The backend lacks specific API endpoints to fetch properties using projectId and to update specific objects (sites, buildings, apartments, garages).

**Comment by HassanAlhawari1998** [comment]
The Property Endpoint returns a JSON object with an empty Property list, indicating a bug in the implementation.

![image](https://github.com/remsfal/remsfal-backend/assets/136626689/0f85f6d1-1c1b-40d0-a82a-8a278ea9d86a)

**Comment by astanik** [comment]
@HassanAlhawari1998 Are you sure you have already created a property?

If not, this behavior is fine for me since total and size are 0.

**Comment by HassanAlhawari1998** [comment]
@astanik there are issues with PropertyItemJSON not being nullable and with RepositoryProperty not returning correct results in findPropertyByProjectId. The getEntityManager.createNamedQuery always returns an empty list, but the query works correctly when called directly without using createNamedQuery.

**Comment by astanik** [comment]
@HassanAlhawari1998 I found an error with the total value being returned. Your problem seems to be the offset you are passing as a query parameter. For an offset of 10 you would expect objects from 10 to 19.
