### ISSUE TITLE
Write a HowTo import eclipse-js-formater.xml

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#193]
https://github.com/remsfal/remsfal-backend/blob/852cc4cec4b958a840a8bafc6eaf1de0bd19bd21/formatter/README.md?plain=1#L6

**Comment by ElsarChabaev** [comment]
Gerne bearbeite ich vorliegendes Thema - vielen Dank

**Comment by ElsarChabaev** [comment]
https://github.com/remsfal/remsfal-backend/pull/252

Nicht sicher ob alles beim pull request alles geklappt hat, deswegen hier nochmal die Änderungen in der README:
https://github.com/remsfal/remsfal-backend/compare/main...ElsarChabaev:remsfal-backend:main
