### ISSUE TITLE
Initial Webchat API

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#213]
The API should provide the following functionalities:

- (POST) Create a text message
- (POST) Uplead a picture
- (GET) Retrieve chat history
- (GET) Download a picture

The API should be placed at /api/v1/projects/{projectId}/tasks/{taskId}/chat
and for defects at /api/v1/projects/{projectId}/defects/{defectId}/chat

**Comment by ArniBananii** [comment]
first issue claimed.

**Comment by parhamrahmani** [comment]
@ArniBananii I am already working on this issue since October, related to my thesis issue `https://github.com/remsfal/remsfal-backend/issues/59`

**Comment by parhamrahmani** [comment]
@astanik I think this issue can be closed and further issues/fixes on [this PR](https://github.com/remsfal/remsfal-backend/pull/239) can be done in separate issues, since the PR has become very huge.
