### ISSUE TITLE
Implementing Image upload/download and storage solution on top of the chat functionality

### ISSUE THREAD

**Issue by parhamrahmani** [remsfal/remsfal-backend#259]
### Description

Enhancing the issue #239  and Related to issue #59 

- Implementation of image upload and download endpoints for the web-chat functionality
- Implementation of a storage solution for the images

**Comment by parhamrahmani** [comment]
I will be working on this issue myself

**Comment by astanik** [comment]
Doku: https://docs.quarkiverse.io/quarkus-minio/dev/index.html
There seems to be a native integration with MINIO, including Dev Services and Test Containers.

@parhamrahmani Can you please update the docker-compose file as well?

**Comment by parhamrahmani** [comment]
@astanik Thank you for the tips. I will make a small PR for the docker compose before the bigger PR that implements the FIleStorageService that works with the MinIO buckets and the download/upload endpoints
