### ISSUE TITLE
Add project members when a new project is created

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#44]
https://github.com/remsfal/remsfal-backend/blob/0307cc7ab59182efef0defedbbac6fbd5dcf1514/remsfal-service/src/main/java/de/remsfal/service/control/ProjectController.java#L62

**Comment by PiaSophieBe** [comment]
Is this bug still a problem? When I tried it, my user was added to the project as a member. 
<img width="749" alt="Bildschirmfoto 2024-05-10 um 23 14 18" src="https://github.com/remsfal/remsfal-backend/assets/166516116/1f541633-7a97-4068-8f2b-2e157886c52b">

**Comment by basselali97** [comment]
first issue claimed

**Comment by astanik** [comment]
This issue is obsolete.
