### ISSUE TITLE
Add shields.io Badges to README file

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#65]

**Comment by Melodycel** [comment]
There could be a badge that shows that the build is passing and another that displays the version.

**Comment by astanik** [comment]
A badge with the number of contributors would be interesting as well.

**Comment by astanik** [comment]
The version badge should display the release version, e.g. https://shields.io/badges/git-hub-release

However, Issue #34 has not been processed yet. We could create a PR without the version badge and create a new Issue for the realese version badge?
