### ISSUE TITLE
Remove 'version' from docker-compose.yml as it is obsolete

### ISSUE THREAD

**Issue by mzudse** [remsfal/remsfal-backend#84]
> The top-level version property is defined by the Compose Specification for backward compatibility. It is only informative and you'll receive a warning message that it is obsolete if used.
Compose doesn't use version to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented.

https://docs.docker.com/compose/compose-file/04-version-and-name/

https://github.com/remsfal/remsfal-backend/blob/a3266b5c67d34bb5c197bdfd634a3fdf3b9c7b9d/docker-compose.yml#L1

**Comment by ruppfabian1997** [comment]
#95 i created a pull request to fix this issue.
