### ISSUE TITLE
Returns Optional's in DAO's/Repositories

### ISSUE THREAD

**Issue by mzudse** [remsfal/remsfal-backend#90]
We could return a Optional<T> instead of a object directly. Then we could remove the null checks and improve the code readability.

```

userEntity.isPresent() // userEntity.isEmpty()
vs
userEntity != null // userEntity == null

```

```
public UserEntity findByEmail(final String email) {
    return find("email", email).singleResult();
}

public Optional<UserEntity> findByEmail(final String email) {
    return Optional.ofNullable(find("email", email).singleResult());
}
```

The PanacheRepositoryBase already contains the method 'findByIdOptional' as an alternative of 'findById'

**Comment by PiaSophieBe** [comment]
Good idea, the use of optinals definitely looks better than lots of null checks!

**Comment by astanik** [comment]
This is a great idea, if we only talk about the return types of repositories. This would only affect the null checks in the controller layer, right?

**Comment by astanik** [comment]
@mzudse Could you please create a real discussion as showcase for our lecture?

<img width="1584" alt="Bildschirmfoto 2024-05-25" src="https://github.com/remsfal/remsfal-backend/assets/7569599/38a05ac1-b3cb-4f46-adeb-d6870ecc8145">

**Comment by mzudse** [comment]
> This is a great idea, if we only talk about the return types of repositories. This would only affect the null checks in the controller layer, right?

Yeah, only the repositories and yes, only the controller layer from what i saw.



> @mzudse Could you please create a real discussion as showcase for our lecture?
> <img alt="Bildschirmfoto 2024-05-25" width="1584" src="https://private-user-images.githubusercontent.com/7569599/333778063-38a05ac1-b3cb-4f46-adeb-d6870ecc8145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTkyNTYsIm5iZiI6MTcxNjY1ODk1NiwicGF0aCI6Ii83NTY5NTk5LzMzMzc3ODA2My0zOGEwNWFjMS1iM2NiLTRmNDYtYWRlYi1kNjg3MGVjYzgxNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTc0MjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRjMzdjZGE5YTgyMjc5YzFkMjFjODQ2OGI1NjNlNjE5ZGMxYmQzNjlhMTEyZjU2ZTlhYjgyNDJmMGJjZmY4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3hXhv0mqMjQlC5t-w0DRFAmjj2Oi8Pdd976M1GEcYr0">

See https://github.com/remsfal/remsfal-backend/discussions/106

**Comment by mzudse** [comment]
I would like to solve this issue
