### ISSUE TITLE
Code formatting settings in IDE's

### ISSUE THREAD

**Issue by mzudse** [remsfal/remsfal-backend#91]
Since different developers are working on the project, the code formatting in IDE's should be standardized.

IDE's:
- Eclipse
- IntelliJ

A common method is to use the Eclipse formatting scheme, which can be imported into an IntelliJ project.

https://github.com/redhat-developer/vscode-java/blob/master/formatters/eclipse-formatter.xml
https://blog.jetbrains.com/idea/2014/01/intellij-idea-13-importing-code-formatter-settings-from-eclipse/

**Comment by astanik** [comment]
Great, this could be KBA Issue.

**Comment by mzudse** [comment]
I would like to solve this KBA
