### ISSUE TITLE
Specify project name in docker-compose.yml

### ISSUE THREAD

**Issue by Tobiwue** [remsfal/remsfal-backend#96]
A project name should be specified in the
[remsfal-backend/docker-compose.yml](https://github.com/remsfal/remsfal-backend/blob/a3266b5c67d34bb5c197bdfd634a3fdf3b9c7b9d/docker-compose.yml)
file.
Reasons for that could be:
1. It is easier to distinguish between multiple docker applications.
2. The name tag helps identify log entries and error messages.
3. Everyone knows exactly what service is being talked about.
4. and lastly obvioulsy scaling 

Further reasons and use cases can be found here:
https://docs.docker.com/compose/project-name/

**Comment by PiaSophieBe** [comment]
I would like to work on this issue.

**Comment by astanik** [comment]
#116
